# set the dist to bionic
dist: bionic
language: node_js
node_js:
  - '10.19'
  - '12.18'
os:
  - linux
  - osx
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
cache:
  npm: false
  yarn: false
if: NOT (branch = master AND type = push AND tag IS blank AND os = osx)
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        wget https://dl.min.io/server/minio/release/linux-amd64/minio;
        chmod 755 minio;
        ./minio server /data;
    else
        wget https://dl.min.io/server/minio/release/darwin-amd64/minio;
        chmod 755 minio;
        ./minio server /data;
    fi
  - yarn build
  - yarn global add teraslice-cli
script:
  - yarn test
  - yarn lint
  - teraslice-cli assets build
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
